version: "3.8"
services:
  db:
    image: mysql:8.4
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=sqlsql
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3396:3306
    volumes:
      - ./dbsql:/var/lib/mysql
  phpDb:
    image: phpmyadmin:5.2
    restart: always
    # environment:
    #   - PMA_ARBITRARY=1
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      # - PMA_USER=root
      # - PMA_PASSWORD=admin
    ports:
      - 8080:80
