version: "3.8"
services:
  db:
    image: mysql:8.4
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=sqlsql
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3396:3306"
    volumes:
      - ./dbsql:/var/lib/mysql
